#!/usr/bin/env bash


# -f bestaudio \
#
/usr/local/bin/yt-dlp \
-x --audio-format mp3 \
-o "%(channel)s - %(title)s.%(ext)s" "$@" \
--download-archive downloaded.txt \
--retries 20 \
--retry-sleep exp=1:2 \
--fragment-retries 20 \
--file-access-retries 3 \
--sponsorblock-remove "all" \
--concurrent-fragments $(nproc) \
--no-check-certificate \
--write-thumbnail \
--add-metadata \
--write-description \
--embed-thumbnail
